services:
  - type: web
    name: insurance-predictor
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd app/app && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free